In [175]:
####1) Importing the datasets

In [176]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [177]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [178]:
df = pd.read_excel('C:/Users/ujjaw/Desktop/Ujjawal/ISB/FP1/CompanyNewsHeadlines_ICICI_Consolidated.xls')
df.head()


Company                 Date  \
0     IBN  2024-01-04 00:00:00   
1     IBN  2024-01-04 00:00:00   
2     IBN  2024-01-04 00:00:00   
3     IBN  2024-01-04 00:00:00   
4     IBN  2024-01-04 00:00:00   

                                          tweet_text Azure label     Score  \
0  IBN Stock Earnings: ICICI Bank Reported Result...    positive  0.728372   
1  IBN Stock Earnings: ICICI Bank Beats EPS for Q...    positive  0.769400   
2   12 Asian Countries with the Best Quality of Life    positive  0.872366   
3  Zacks Industry Outlook Highlights Mitsubishi U...    positive  0.602522   
4  Higher Rates to Aid HSBC's Q3 Earnings, IB &Tr...     neutral  0.531279   

  TextBlob Label   Comparision  
0        Neutral  Do not match  
1        Neutral  Do not match  
2       Positive         Match  
3        Neutral  Do not match  
4       Positive  Do not match

In [179]:
df.head(1500)

Company                         Date  \
0         IBN          2024-01-04 00:00:00   
1         IBN          2024-01-04 00:00:00   
2         IBN          2024-01-04 00:00:00   
3         IBN          2024-01-04 00:00:00   
4         IBN          2024-01-04 00:00:00   
...       ...                          ...   
1495  Twitter   Nov 3, 2023 · 4:18 PM UTC   
1496  Twitter   Nov 3, 2023 · 2:39 PM UTC   
1497  Twitter  Nov 3, 2023 · 11:03 AM UTC   
1498  Twitter  Nov 3, 2023 · 10:56 AM UTC   
1499  Twitter  Nov 3, 2023 · 10:50 AM UTC   

                                             tweet_text Azure label     Score  \
0     IBN Stock Earnings: ICICI Bank Reported Result...    positive  0.728372   
1     IBN Stock Earnings: ICICI Bank Beats EPS for Q...    positive  0.769400   
2      12 Asian Countries with the Best Quality of Life    positive  0.872366   
3     Zacks Industry Outlook Highlights Mitsubishi U...    positive  0.602522   
4     Higher Rates to Aid HSBC's Q3 Earnings, IB &Tr...     neutral  0.531279   
...                                                 ...         ...       ...   
1495  Sony Bravia 164 cm (65 inches) 4K Ultra HD Sma...     neutral  0.450014   
1496  @Icicidirectcare @ICICIBank_Care @Vijaychandok...    positive  0.688278   
1497  👉 Buying a home could get expensive  👉 U...    positive  0.739117   
1498  Fraud #icici first Learn to respond customer c...    negative  0.424363   
1499  @Icicidirectcare @ICICIBank_Care @Vijaychandok...    negative  0.132052   

     TextBlob Label   Comparision  
0           Neutral  Do not match  
1           Neutral  Do not match  
2          Positive         Match  
3           Neutral  Do not match  
4          Positive  Do not match  
...             ...           ...  
1495       Positive  Do not match  
1496       Negative  Do not match  
1497       Negative  Do not match  
1498       Negative         Match  
1499       Negative         Match  

[1500 rows x 7 columns]

In [180]:
# Drop columns 
columns_to_drop = ['Company', 'Date','Score','TextBlob Label','Comparision']
df = df.drop(columns=columns_to_drop)

In [181]:
df

tweet_text Azure label
0     IBN Stock Earnings: ICICI Bank Reported Result...    positive
1     IBN Stock Earnings: ICICI Bank Beats EPS for Q...    positive
2      12 Asian Countries with the Best Quality of Life    positive
3     Zacks Industry Outlook Highlights Mitsubishi U...    positive
4     Higher Rates to Aid HSBC's Q3 Earnings, IB &Tr...     neutral
...                                                 ...         ...
1863  #ICICI #LOMBARD #GENERAL #INSURANCE: Q2  NET P...    positive
1864  ICICI Bank violates norms relating to Loans an...    positive
1865  RBI issues penalties worth 17cr to ICICI Bank ...    positive
1866  I have already sent my contact number. Note th...    negative
1867  नुकसानीच्या सर्व...    positive

[1868 rows x 2 columns]

In [182]:
df['Azure label'].value_counts()

Azure label
positive    1049
neutral      419
negative     400
Name: count, dtype: int64

In [183]:
# check for null values
df.isnull().sum()
df=df.dropna()
df = df.reset_index(drop=True)

# no null values in the data

In [184]:
####2) Data Cleaning
# here we will remove stopwords, punctuations
# as well as we will apply lemmatization

In [185]:
import re
clean =  re.compile('<.*?>')
re.sub(clean,'',df.iloc[200].tweet_text)

'The six-member monetary policy committee kept repo rates unchanged at 6.5 percent in the December meeting...'

In [186]:
def clean_html(text):
    clean =  re.compile('<.*?>')
    return  re.sub(clean, '' , text)

In [187]:
df['tweet_text'] = df['tweet_text'].apply(clean_html)

In [188]:
##function to remove special character. 

def remove_special(tweet_text):
    if tweet_text is None:
        return None
    x=''

    for  i in tweet_text:
        if i.isalnum():
            x=x+i
        elif i.isspace():
            x=x+' '
        else:
            x=x +  ''
    return x

In [189]:
df['tweet_text'] = df['tweet_text'].apply(remove_special)

In [190]:
import re

def remove_non_ascii(text):
    return re.sub(r'[^\x00-\x7F]+', '', text)

# Example usage
original_text = "नुकसानीà¤&^%^%$^šà¥à¤¯à¤¾ सर्à¤"
cleaned_text = remove_non_ascii(original_text)

print("Original Text:", original_text)
print("Cleaned Text:", cleaned_text)

Original Text: नुकसानीà¤&^%^%$^šà¥à¤¯à¤¾ सर्à¤
Cleaned Text: &^%^%$^ 


In [191]:
df['tweet_text'] = df['tweet_text'].apply(remove_non_ascii)

In [192]:
df

tweet_text Azure label
0     IBN Stock Earnings ICICI Bank Reported Results...    positive
1     IBN Stock Earnings ICICI Bank Beats EPS for Q1...    positive
2      12 Asian Countries with the Best Quality of Life    positive
3     Zacks Industry Outlook Highlights Mitsubishi U...    positive
4     Higher Rates to Aid HSBCs Q3 Earnings IB Tradi...     neutral
...                                                 ...         ...
1863  ICICI LOMBARD GENERAL INSURANCE Q2  NET PROFIT...    positive
1864  ICICI Bank violates norms relating to Loans an...    positive
1865  RBI issues penalties worth 17cr to ICICI Bank ...    positive
1866  I have already sent my contact number Note tha...    negative
1867        ICICI          httpsnews15marathicombyfo...    positive

[1868 rows x 2 columns]

In [193]:
df.describe()

tweet_text Azure label
count                                                1868        1868
unique                                               1443           3
top     The banks asset quality improved as the gross ...    positive
freq                                                   45        1049

In [194]:
from bs4 import BeautifulSoup
import re

In [195]:
df['tweet_text'] = df['tweet_text'].apply(lambda x: BeautifulSoup(x).get_text())
df['tweet_text'] = df['tweet_text'].apply(lambda x: re.sub(r'http\S+', '', x))

In [196]:
import re

def contractions(s):
    s = re.sub(r"won't", 'will not', s)
    s = re.sub(r"wouldn't", 'would not', s)
    s = re.sub(r"couldn't", 'could not', s)
    s = re.sub(r"can't", 'can not', s)
    s = re.sub(r"n't", ' not', s)
    s = re.sub(r"'d", ' would', s)
    s = re.sub(r"'re", ' are', s)
    s = re.sub(r"'s", ' is', s)
    s = re.sub(r"'ll", ' will', s)
    s = re.sub(r"'t", ' not', s)
    s = re.sub(r"'ve", ' have', s)
    s = re.sub(r"'m", ' am', s)
    return s

# Assuming 'tweet_text' is the column containing text data in your DataFrame
df['tweet_text'] = df['tweet_text'].apply(contractions)

In [197]:
df

tweet_text Azure label
0     IBN Stock Earnings ICICI Bank Reported Results...    positive
1     IBN Stock Earnings ICICI Bank Beats EPS for Q1...    positive
2      12 Asian Countries with the Best Quality of Life    positive
3     Zacks Industry Outlook Highlights Mitsubishi U...    positive
4     Higher Rates to Aid HSBCs Q3 Earnings IB Tradi...     neutral
...                                                 ...         ...
1863  ICICI LOMBARD GENERAL INSURANCE Q2  NET PROFIT...    positive
1864  ICICI Bank violates norms relating to Loans an...    positive
1865  RBI issues penalties worth 17cr to ICICI Bank ...    positive
1866  I have already sent my contact number Note tha...    negative
1867                                    ICICI              positive

[1868 rows x 2 columns]

In [198]:
import nltk

In [199]:
df['tweet_text']=df['tweet_text'].apply(lambda x: ' '.join([re.sub('[^A-Za-z]+','', x) for x in nltk.word_tokenize(x)]))

In [200]:
df

tweet_text Azure label
0     IBN Stock Earnings ICICI Bank Reported Results...    positive
1        IBN Stock Earnings ICICI Bank Beats EPS for Q     positive
2         Asian Countries with the Best Quality of Life    positive
3     Zacks Industry Outlook Highlights Mitsubishi U...    positive
4     Higher Rates to Aid HSBCs Q Earnings IB Tradin...     neutral
...                                                 ...         ...
1863  ICICI LOMBARD GENERAL INSURANCE Q NET PROFIT B...    positive
1864  ICICI Bank violates norms relating to Loans an...    positive
1865  RBI issues penalties worth cr to ICICI Bank an...    positive
1866  I have already sent my contact number Note tha...    negative
1867                                              ICICI    positive

[1868 rows x 2 columns]

In [201]:
df['tweet_text']=df['tweet_text'].apply(lambda x: re.sub(' +', ' ', x))

In [202]:
df

tweet_text Azure label
0     IBN Stock Earnings ICICI Bank Reported Results...    positive
1        IBN Stock Earnings ICICI Bank Beats EPS for Q     positive
2         Asian Countries with the Best Quality of Life    positive
3     Zacks Industry Outlook Highlights Mitsubishi U...    positive
4     Higher Rates to Aid HSBCs Q Earnings IB Tradin...     neutral
...                                                 ...         ...
1863  ICICI LOMBARD GENERAL INSURANCE Q NET PROFIT B...    positive
1864  ICICI Bank violates norms relating to Loans an...    positive
1865  RBI issues penalties worth cr to ICICI Bank an...    positive
1866  I have already sent my contact number Note tha...    negative
1867                                              ICICI    positive

[1868 rows x 2 columns]

In [203]:
df['tweet_text']

0       IBN Stock Earnings ICICI Bank Reported Results...
1          IBN Stock Earnings ICICI Bank Beats EPS for Q 
2           Asian Countries with the Best Quality of Life
3       Zacks Industry Outlook Highlights Mitsubishi U...
4       Higher Rates to Aid HSBCs Q Earnings IB Tradin...
                              ...                        
1863    ICICI LOMBARD GENERAL INSURANCE Q NET PROFIT B...
1864    ICICI Bank violates norms relating to Loans an...
1865    RBI issues penalties worth cr to ICICI Bank an...
1866    I have already sent my contact number Note tha...
1867                                                ICICI
Name: tweet_text, Length: 1868, dtype: object

In [204]:
import string

In [205]:
punct = string.punctuation

In [206]:
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [207]:
from spacy.lang.en.stop_words import STOP_WORDS

In [208]:
stopwords = list(STOP_WORDS) # list of stopwords

In [209]:
# creating a function for data cleaning

In [210]:
def text_data_cleaning(sentence):
  doc = nlp(sentence)

  tokens = [] # list of tokens
  for token in doc:
    if token.lemma_ != "-PRON-":
      temp = token.lemma_.lower().strip()
    else:
      temp = token.lower_
    tokens.append(temp)
 
  cleaned_tokens = []
  for token in tokens:
    if token not in stopwords and token not in punct:
      cleaned_tokens.append(token)
  return cleaned_tokens

In [211]:
# if root form of that word is not pronoun then it is going to convert that into lower form
# and if that word is a proper noun, then we are directly taking lower form, because there is no lemma for proper noun

In [212]:
text_data_cleaning("Hello all, It's a beautiful day outside there!")
# stopwords and punctuations removed

['hello', 'beautiful', 'day', 'outside']

In [213]:
df['tweet_text'] = df['tweet_text'].apply(text_data_cleaning)

In [214]:
df['tweet_text']

0       [ibn, stock, earnings, icici, bank, report, re...
1       [ibn, stock, earnings, icici, bank, beats, eps...
2                 [asian, countries, best, quality, life]
3       [zacks, industry, outlook, highlights, mitsubi...
4       [high, rate, aid, hsbcs, q, earnings, ib, trad...
                              ...                        
1863    [icici, lombard, general, insurance, q, net, p...
1864    [icici, bank, violate, norm, relate, loans, ad...
1865    [rbi, issue, penalty, worth, cr, icici, bank, ...
1866    [send, contact, number, note, issue, fraudulen...
1867                                              [icici]
Name: tweet_text, Length: 1868, dtype: object

In [215]:
# Perform Stemming
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [216]:
y = []
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z
    

In [217]:
df['tweet_text'] = df['tweet_text'].apply(stem_words)

In [218]:
def join_back(list_input):
    return " ".join(list_input)

In [219]:
df['tweet_text'] = df['tweet_text'].apply(join_back)

In [220]:
df['tweet_text']

0               ibn stock earn icici bank report result q
1                     ibn stock earn icici bank beat ep q
2                         asian countri best qualiti life
3       zack industri outlook highlight mitsubishi ufj...
4                 high rate aid hsbc q earn ib trade hurt
                              ...                        
1863    icici lombard gener insur q net profit b vs b ...
1864    icici bank violat norm relat loan advanc rbi i...
1865    rbi issu penalti worth cr icici bank kotak mah...
1866    send contact number note issu fraudul debit ac...
1867                                                icici
Name: tweet_text, Length: 1868, dtype: object

In [221]:
# This is the clean and processed data.
df

tweet_text Azure label
0             ibn stock earn icici bank report result q    positive
1                   ibn stock earn icici bank beat ep q    positive
2                       asian countri best qualiti life    positive
3     zack industri outlook highlight mitsubishi ufj...    positive
4               high rate aid hsbc q earn ib trade hurt     neutral
...                                                 ...         ...
1863  icici lombard gener insur q net profit b vs b ...    positive
1864  icici bank violat norm relat loan advanc rbi i...    positive
1865  rbi issu penalti worth cr icici bank kotak mah...    positive
1866  send contact number note issu fraudul debit ac...    negative
1867                                              icici    positive

[1868 rows x 2 columns]

In [222]:
# Bag of Words Model (Feature Extraction)
#Countvectorizer
#TF-IDF Vectorizer

In [223]:
df.shape

(1868, 2)

In [224]:
from sklearn.feature_extraction.text import CountVectorizer

CV = CountVectorizer()
CV_features = CV.fit_transform(df['tweet_text'])

In [225]:
CV_features.shape

(1868, 4375)

In [226]:
CV_features[0]

<1x4375 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [227]:
type(CV_features[0])  # each row is a compressed spare row 

scipy.sparse._csr.csr_matrix

In [174]:
CV_features[0].todense()  # decompressing the CSR data

matrix([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [228]:
import pandas as pd
df1 = pd.DataFrame(CV_features.todense() )
df1
# Document-Term-Matrix X = [N x p ]
# N = no. of documentns
# p = no. of unique words in the vocab!!# this is your D

0     1     2     3     4     5     6     7     8     9     ...  4365  \
0        0     0     0     0     0     0     0     0     0     0  ...     0   
1        0     0     0     0     0     0     0     0     0     0  ...     0   
2        0     0     0     0     0     0     0     0     0     0  ...     0   
3        0     0     0     0     0     0     0     0     0     0  ...     0   
4        0     0     0     0     0     0     0     0     0     0  ...     0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
1863     0     0     0     0     0     0     0     0     0     0  ...     0   
1864     0     0     0     0     0     0     0     0     0     0  ...     0   
1865     0     0     0     0     0     0     0     0     0     0  ...     0   
1866     0     0     0     0     0     0     0     0     0     0  ...     0   
1867     0     0     0     0     0     0     0     0     0     0  ...     0   

      4366  4367  4368  4369  4370  4371  4372  4373  4374  
0        0     0     0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0     0     0  
2        0     0     0     0     0     0     0     0     0  
3        0     0     0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
1863     0     0     0     0     0     0     0     0     0  
1864     0     0     0     0     0     0     0     0     0  
1865     0     0     0     0     0     0     0     0     0  
1866     0     0     0     0     0     0     0     0     0  
1867     0     0     0     0     0     0     0     0     0  

[1868 rows x 4375 columns]

In [229]:
df1.size/1e6  # these many elements/numbers are presnt in the df

8.1725

In [230]:
import numpy as np
np.count_nonzero(df1)

27194

In [231]:
100*np.count_nonzero(df1)/df1.size # percent of the non-zero elements i nthe df

0.33275007647598653

In [232]:
#print(CV.get_feature_names()[:50])  # these the vocab words
print(CV.get_feature_names_out()[:50])

['aadhaar' 'aag' 'aajnew' 'aajtak' 'aakhi' 'aarti' 'aaya' 'abhi' 'abil'
 'abl' 'ablew' 'abpananda' 'abpliv' 'abpnew' 'abruptli' 'absl' 'abslmf'
 'absolut' 'abt' 'ac' 'acc' 'accentur' 'accept' 'access' 'accord'
 'account' 'accountabsurd' 'accountbut' 'accountyatra' 'acct' 'accumul'
 'accur' 'accuraci' 'accus' 'acer' 'achiev' 'acknowledg' 'acno' 'acquir'
 'acquisit' 'acro' 'act' 'action' 'activ' 'activis' 'activist' 'actual'
 'acuman' 'ad' 'ada']


In [233]:
# len(CV.get_feature_names_out())
len(CV.get_feature_names_out())

4375

In [234]:
CV_features[10].todense()  # these are numbers corresponding to the 11th tweet

matrix([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [235]:
CV.inverse_transform(np.asarray(CV_features[10].todense()))  # actual words in the 10th tweet

[array(['amid', 'bank', 'cost', 'high', 'ibn', 'icici', 'loan', 'rate',
        'ride', 'woe'], dtype='<U104')]

In [236]:
# 5. Model building

In [237]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(CV_features, df['Azure label'], test_size=0.25, stratify=df['Azure label'], random_state=42)

In [238]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(solver='liblinear')
LR.fit(X_train, y_train)

print(LR.score(X_train, y_train))  # train score)
print(LR.score(X_test, y_test))   # test score)   

0.9735902926481085
0.7794432548179872


In [239]:
## L1-REGULARIZATION
LR1 = LogisticRegression(class_weight='balanced', solver='liblinear', penalty='l1', C=0.4)
LR1.fit(X_train, y_train)

print(LR1.score(X_train, y_train))  # train score)
print(LR1.score(X_test, y_test))   # test score)  

0.820842255531763
0.7944325481798715


In [240]:
## leT'S Cross-Validate the Logistic Regression Model ?????
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.model_selection import StratifiedKFold

In [242]:
X = CV_features
y = df['Azure label']

In [243]:
## crOSS VALIDATE THE LR1 model

LR1 = LogisticRegression(class_weight='balanced', solver='liblinear', penalty='l1', C=0.4)
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
results = cross_val_score(LR1, X, y, cv=kfold, scoring='accuracy')
print(results)
print(np.round((results.mean())*100, 2), np.round((results.std())*100, 2)) 

[0.78342246 0.78609626 0.77272727 0.71849866 0.76675603]
76.55 2.45


In [244]:
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
results = cross_validate(LR1, X, y, cv=kfold, scoring='accuracy', return_train_score=True)

In [245]:
results

{'fit_time': array([0.01035285, 0.01099706, 0.00897908, 0.00999808, 0.00899673]),
 'score_time': array([0.        , 0.        , 0.00100088, 0.        , 0.        ]),
 'test_score': array([0.78342246, 0.78609626, 0.77272727, 0.71849866, 0.76675603]),
 'train_score': array([0.8206158 , 0.81994645, 0.82128514, 0.82541806, 0.83344482])}

In [246]:
print(results['train_score'])
print(np.round((results['train_score'].mean())*100, 2), np.round((results['train_score'].std())*100, 2)) 

[0.8206158  0.81994645 0.82128514 0.82541806 0.83344482]
82.41 0.5


In [247]:
print(results['test_score'])
print(np.round((results['test_score'].mean())*100, 2), np.round((results['test_score'].std())*100, 2)) 

[0.78342246 0.78609626 0.77272727 0.71849866 0.76675603]
76.55 2.45


In [250]:
# Create a pipeline & cross-validate
from sklearn.pipeline import make_pipeline, Pipeline

X = df['tweet_text']
y = df['Azure label']

CV = CountVectorizer()
LR1 = LogisticRegression(class_weight='balanced', solver='liblinear', penalty='l1', C=0.4)

CV_pipe = Pipeline([('CV', CV) , ('LR', LR1)] )

results = cross_val_score(CV_pipe, X, y, cv=kfold, scoring='accuracy')
print(np.round((results.mean())*100, 2), np.round((results.std())*100, 2)) 

76.5 2.42


In [251]:
CV_pipe.named_steps

{'CV': CountVectorizer(),
 'LR': LogisticRegression(C=0.4, class_weight='balanced', penalty='l1',
                    solver='liblinear')}

In [252]:
CV_pipe.fit(X,y)

Pipeline(steps=[('CV', CountVectorizer()),
                ('LR',
                 LogisticRegression(C=0.4, class_weight='balanced',
                                    penalty='l1', solver='liblinear'))])

In [253]:
len(CV_pipe['CV'].vocabulary_)  # CV with stopwords applied already & word_len > 2

4375

In [254]:
import joblib
joblib.__version__

'1.2.0'

In [255]:
!pip install mglearn
import mglearn

In [257]:
df.to_pickle("Sentiment_Analysis.pkl")